version: '3.1'
services:
  stats-server:
    build: stat-service/server/
    image: stats
    container_name: ewm_stats_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
      SPRING_DATASOURCE_USERNAME: klingTone
      SPRING_DATASOURCE_PASSWORD: 12345

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - 6541:5432
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: klingTone
      POSTGRES_PASSWORD: 12345

  ewm-service:
    build: main-service/
    image: main
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
    environment:
      EWM_STAT_SERVER_URL: http://stats-server:9090/
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: klingTone
      SPRING_DATASOURCE_PASSWORD: 12345

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - 6542:5432
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: klingTone
      POSTGRES_PASSWORD: 12345